#!/bin/bash

# $Header: /u/gcmpack/MITgcm/tools/build_options/linux_amd64_ifort+mpi_yxzhang,v 1.0 2013/6/19 19:14:14 jmc Exp $
# $Name: checkpoint64g $

# ----------------------------------------------------------------------------
# FOR MITgcm COMPILATION ON CLUSTER MYNODE
# Last updated: HP 04/08/10
# ----------------------------------------------------------------------------

FC=mpif77
CC=mpicc
LINK=mpif77

CPP='/usr/bin/cpp -P -traditional'
MPI='true'

#FFLAGS='-fPIC -r8 -i4 -WB -convert big_endian -assume byterecl'
FFLAGS='-r8 -i4 -WB -convert big_endian -assume byterecl -mcmodel=medium -shared-intel -g'
FOPTIM='-O3 -xssse3'

F90FLAGS=$FFLAGS
F90OPTIM=$FOPTIM

#CFLAGS='-O3 -xssse3 -ip -fPIC'
CFLAGS='-03 -xssse3 -ip'

DEFINES='-DALLOW_USE_MPI -DWORDLENGTH=4'

# --------------------------
# INCLUDE NETCDF DIRECTORIES
# --------------------------
INCLUDEDIRS=""
INCLUDES="/opt/netcdf-3.6.2/include"
LIBS="/opt/netcdf-3.6.2/lib -lnetcdf -lmpi"

# -----------------------
# INCLUDE MPI DIRECTORIES
# -----------------------
INCLUDES="/opt/openmpi-1.2.6/include"
INCLUDEDIRS="/opt/openmpi-1.2.6/include"
MPIINCLUDEDIR="/opt/openmpi-1.2.6/include"
LIBS="/opt/openmpi-1.2.6/lib"
MPI_HEADER_FILES='mpif.h mpiof.h mpif_parameters.h'
MPI_HEADER_FILES_INC='mpi_headers/mpif.h mpi_headers/mpiof.h mpi_headers/mpif_parameters.h'